# Generated by Django 3.0 on 2019-12-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='Deskripsi',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
