# Generated by Django 3.0 on 2019-12-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecode', '0002_barang_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='Deskripsi',
            field=models.CharField(max_length=200),
        ),
    ]
