# Generated by Django 3.0 on 2019-12-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecode', '0003_auto_20191212_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='Deskripsi',
            new_name='Deskripsi1',
        ),
        migrations.AddField(
            model_name='barang',
            name='Deskripsi2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='barang',
            name='Deskripsi3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
